mn1b=$(/usr/local/bin/dogecash-cli -conf=/home/doge_mn1/.dogecash/dogecash.conf -datadir=/home/doge_mn1/.dogecash/ getinfo | grep blocks)
mn1s=$(/usr/local/bin/dogecash-cli -conf=/home/doge_mn1/.dogecash/dogecash.conf -datadir=/home/doge_mn1/.dogecash/ getmasternodestatus | grep message)
mn2b=$(/usr/local/bin/dogecash-cli -conf=/home/doge_mn2/.dogecash/dogecash.conf -datadir=/home/doge_mn2/.dogecash/ getinfo | grep blocks)
mn2s=$(/usr/local/bin/dogecash-cli -conf=/home/doge_mn2/.dogecash/dogecash.conf -datadir=/home/doge_mn2/.dogecash/ getmasternodestatus | grep message)
mn3b=$(/usr/local/bin/dogecash-cli -conf=/home/doge_mn3/.dogecash/dogecash.conf -datadir=/home/doge_mn3/.dogecash/ getinfo | grep blocks)
mn3s=$(/usr/local/bin/dogecash-cli -conf=/home/doge_mn3/.dogecash/dogecash.conf -datadir=/home/doge_mn3/.dogecash/ getmasternodestatus | grep message)
mn4b=$(/usr/local/bin/dogecash-cli -conf=/home/doge_mn4/.dogecash/dogecash.conf -datadir=/home/doge_mn4/.dogecash/ getinfo | grep blocks)
mn4s=$(/usr/local/bin/dogecash-cli -conf=/home/doge_mn4/.dogecash/dogecash.conf -datadir=/home/doge_mn4/.dogecash/ getmasternodestatus | grep message)
mn5b=$(/usr/local/bin/dogecash-cli -conf=/home/doge_mn5/.dogecash/dogecash.conf -datadir=/home/doge_mn5/.dogecash/ getinfo | grep blocks)
mn5s=$(/usr/local/bin/dogecash-cli -conf=/home/doge_mn5/.dogecash/dogecash.conf -datadir=/home/doge_mn5/.dogecash/ getmasternodestatus | grep message)
mn6b=$(/usr/local/bin/dogecash-cli -conf=/home/doge_mn6/.dogecash/dogecash.conf -datadir=/home/doge_mn6/.dogecash/ getinfo | grep blocks)
mn6s=$(/usr/local/bin/dogecash-cli -conf=/home/doge_mn6/.dogecash/dogecash.conf -datadir=/home/doge_mn6/.dogecash/ getmasternodestatus | grep message)
mn7b=$(/usr/local/bin/dogecash-cli -conf=/home/doge_mn7/.dogecash/dogecash.conf -datadir=/home/doge_mn7/.dogecash/ getinfo | grep blocks)
mn7s=$(/usr/local/bin/dogecash-cli -conf=/home/doge_mn7/.dogecash/dogecash.conf -datadir=/home/doge_mn7/.dogecash/ getmasternodestatus | grep message)
mn8b=$(/usr/local/bin/dogecash-cli -conf=/home/doge_mn8/.dogecash/dogecash.conf -datadir=/home/doge_mn8/.dogecash/ getinfo | grep blocks)
mn8s=$(/usr/local/bin/dogecash-cli -conf=/home/doge_mn8/.dogecash/dogecash.conf -datadir=/home/doge_mn8/.dogecash/ getmasternodestatus | grep message)
mn9b=$(/usr/local/bin/dogecash-cli -conf=/home/doge_mn9/.dogecash/dogecash.conf -datadir=/home/doge_mn9/.dogecash/ getinfo | grep blocks)
mn9s=$(/usr/local/bin/dogecash-cli -conf=/home/doge_mn9/.dogecash/dogecash.conf -datadir=/home/doge_mn9/.dogecash/ getmasternodestatus | grep message)
mn10b=$(/usr/local/bin/dogecash-cli -conf=/home/doge_mn10/.dogecash/dogecash.conf -datadir=/home/doge_mn10/.dogecash/ getinfo | grep blocks)
mn10s=$(/usr/local/bin/dogecash-cli -conf=/home/doge_mn10/.dogecash/dogecash.conf -datadir=/home/doge_mn10/.dogecash/ getmasternodestatus | grep message)
mn11b=$(/usr/local/bin/dogecash-cli -conf=/home/doge_mn11/.dogecash/dogecash.conf -datadir=/home/doge_mn11/.dogecash/ getinfo | grep blocks)
mn11s=$(/usr/local/bin/dogecash-cli -conf=/home/doge_mn11/.dogecash/dogecash.conf -datadir=/home/doge_mn11/.dogecash/ getmasternodestatus | grep message)
mn12b=$(/usr/local/bin/dogecash-cli -conf=/home/doge_mn12/.dogecash/dogecash.conf -datadir=/home/doge_mn12/.dogecash/ getinfo | grep blocks)
mn12s=$(/usr/local/bin/dogecash-cli -conf=/home/doge_mn12/.dogecash/dogecash.conf -datadir=/home/doge_mn12/.dogecash/ getmasternodestatus | grep message)
mn13b=$(/usr/local/bin/dogecash-cli -conf=/home/doge_mn13/.dogecash/dogecash.conf -datadir=/home/doge_mn13/.dogecash/ getinfo | grep blocks)
mn13s=$(/usr/local/bin/dogecash-cli -conf=/home/doge_mn13/.dogecash/dogecash.conf -datadir=/home/doge_mn13/.dogecash/ getmasternodestatus | grep message)
mn14b=$(/usr/local/bin/dogecash-cli -conf=/home/doge_mn14/.dogecash/dogecash.conf -datadir=/home/doge_mn14/.dogecash/ getinfo | grep blocks)
mn14s=$(/usr/local/bin/dogecash-cli -conf=/home/doge_mn14/.dogecash/dogecash.conf -datadir=/home/doge_mn14/.dogecash/ getmasternodestatus | grep message)
mn15b=$(/usr/local/bin/dogecash-cli -conf=/home/doge_mn15/.dogecash/dogecash.conf -datadir=/home/doge_mn15/.dogecash/ getinfo | grep blocks)
mn15s=$(/usr/local/bin/dogecash-cli -conf=/home/doge_mn15/.dogecash/dogecash.conf -datadir=/home/doge_mn15/.dogecash/ getmasternodestatus | grep message)
mn16b=$(/usr/local/bin/dogecash-cli -conf=/home/doge_mn16/.dogecash/dogecash.conf -datadir=/home/doge_mn16/.dogecash/ getinfo | grep blocks)
mn16s=$(/usr/local/bin/dogecash-cli -conf=/home/doge_mn16/.dogecash/dogecash.conf -datadir=/home/doge_mn16/.dogecash/ getmasternodestatus | grep message)
mn17b=$(/usr/local/bin/dogecash-cli -conf=/home/doge_mn17/.dogecash/dogecash.conf -datadir=/home/doge_mn17/.dogecash/ getinfo | grep blocks)
mn17s=$(/usr/local/bin/dogecash-cli -conf=/home/doge_mn17/.dogecash/dogecash.conf -datadir=/home/doge_mn17/.dogecash/ getmasternodestatus | grep message)
mn18b=$(/usr/local/bin/dogecash-cli -conf=/home/doge_mn18/.dogecash/dogecash.conf -datadir=/home/doge_mn18/.dogecash/ getinfo | grep blocks)
mn18s=$(/usr/local/bin/dogecash-cli -conf=/home/doge_mn18/.dogecash/dogecash.conf -datadir=/home/doge_mn18/.dogecash/ getmasternodestatus | grep message)
mn19b=$(/usr/local/bin/dogecash-cli -conf=/home/doge_mn19/.dogecash/dogecash.conf -datadir=/home/doge_mn19/.dogecash/ getinfo | grep blocks)
mn19s=$(/usr/local/bin/dogecash-cli -conf=/home/doge_mn19/.dogecash/dogecash.conf -datadir=/home/doge_mn19/.dogecash/ getmasternodestatus | grep message)
mn20b=$(/usr/local/bin/dogecash-cli -conf=/home/doge_mn20/.dogecash/dogecash.conf -datadir=/home/doge_mn20/.dogecash/ getinfo | grep blocks)
mn20s=$(/usr/local/bin/dogecash-cli -conf=/home/doge_mn20/.dogecash/dogecash.conf -datadir=/home/doge_mn20/.dogecash/ getmasternodestatus | grep message)


EXPBLOCK=$(curl -s4 "https://api.dogec.io/api/getblockcount")
echo "Explorer:__________________$EXPBLOCK blocchi"
echo "Masternode 1:  $mn1b - $mn1s "
echo "Masternode 2:  $mn2b - $mn2s "
echo "Masternode 3:  $mn3b - $mn3s "
echo "Masternode 4:  $mn4b - $mn4s "
echo "Masternode 5:  $mn5b - $mn5s "
echo "Masternode 6:  $mn6b - $mn6s "
echo "Masternode 7:  $mn7b - $mn7s "
echo "Masternode 8:  $mn8b - $mn8s "
echo "Masternode 9:  $mn9b - $mn9s "
echo "Masternode 10: $mn10b - $mn10s "
echo "Masternode 11: $mn11b - $mn11s "
echo "Masternode 12: $mn12b - $mn12s "
echo "Masternode 13: $mn13b - $mn13s "
echo "Masternode 14: $mn14b - $mn14s "
echo "Masternode 15: $mn15b - $mn15s "
echo "Masternode 16: $mn16b - $mn16s "
echo "Masternode 17: $mn17b - $mn17s "
echo "Masternode 18: $mn18b - $mn18s "
echo "Masternode 19: $mn19b - $mn19s "
echo "Masternode 20: $mn20b - $mn20s "
